### ISSUE TITLE
pass_through

### ISSUE THREAD

**Issue by liyvfeng** [nickhward/Aubo-Pick-And-Place#1]
Hello, when I run the pass_through file, rivz has no point cloud output in the topic output_cloud_filtered. May I ask what is the problem?

**Comment by speakerholes** [comment]
Can you show me the topics being published after you run the pass_through file?

**Comment by liyvfeng** [comment]
I use the realsense d435 camera. After running the program, the topics are as follows:
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressed/parameter_descriptions
/camera/color/image_raw/compressed/parameter_updates
/camera/color/image_raw/compressedDepth
/camera/color/image_raw/compressedDepth/parameter_descriptions
/camera/color/image_raw/compressedDepth/parameter_updates
/camera/color/image_raw/theora
/camera/color/image_raw/theora/parameter_descriptions
/camera/color/image_raw/theora/parameter_updates
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/color/points
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressed/parameter_descriptions
/camera/depth/image_rect_raw/compressed/parameter_updates
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/image_rect_raw/compressedDepth/parameter_descriptions
/camera/depth/image_rect_raw/compressedDepth/parameter_updates
/camera/depth/image_rect_raw/theora
/camera/depth/image_rect_raw/theora/parameter_descriptions
/camera/depth/image_rect_raw/theora/parameter_updates
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/pointcloud/parameter_descriptions
/camera/pointcloud/parameter_updates
/camera/realsense2_camera_manager/bond
/camera/rgb_camera/auto_exposure_roi/parameter_descriptions
/camera/rgb_camera/auto_exposure_roi/parameter_updates
/camera/rgb_camera/parameter_descriptions
/camera/rgb_camera/parameter_updates
/camera/stereo_module/auto_exposure_roi/parameter_descriptions
/camera/stereo_module/auto_exposure_roi/parameter_updates
/camera/stereo_module/parameter_descriptions
/camera/stereo_module/parameter_updates
/clicked_point
/darknet_ros/bounding_boxes
/darknet_ros/check_for_objects/cancel
/darknet_ros/check_for_objects/feedback
/darknet_ros/check_for_objects/goal
/darknet_ros/check_for_objects/result
/darknet_ros/check_for_objects/status
/darknet_ros/detection_image
/darknet_ros/found_object
/diagnostics
/initialpose
/move_base_simple/goal
/output_filtered_cloud
/rosout
/rosout_agg
/tf
/tf_static

**Comment by speakerholes** [comment]
I don't see any topic here that has the same as mine which was "/camera_remote/depth_registered/points". You're going to have to change line 266 so that it subscribes to the correct topic. Subscribe to which ever topic is publishing the depth data/point could data from your camera at line 266.

Hope this helps! 

Edit: Just so it's more clear - line 266 in pass_through.py

**Comment by liyvfeng** [comment]
Thank you very much for your guidance and I will continue to learn your code.

**Comment by speakerholes** [comment]
Did that fix your problem by chance?
